/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package u04_usabilidad02;

//import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author portatil_profesorado
 */
public class IntroducirReforma extends javax.swing.JDialog {

    /**
     * Creates new form IntroducirReforma
     */
    public IntroducirReforma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
       
        getContentPane().setBackground(new Color(247, 255, 247));
        ImageIcon imagen=new ImageIcon("recursos/EJ01_02.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
        lblImagen.setIcon(icono);
        this.repaint();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCliente = new javax.swing.JPanel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jtextfield1 = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JTextField();
        pnlAcciones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        pnlServicios = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        cbTrabajo = new javax.swing.JComboBox();
        spnCantidad = new javax.swing.JSpinner();
        btnAgregar = new javax.swing.JButton();
        spPresupuesto = new javax.swing.JScrollPane();
        jtPresupuesto = new javax.swing.JTable();
        Menu = new javax.swing.JMenuBar();
        Guardar = new javax.swing.JMenu();
        cbMostrarImagenesMenu = new javax.swing.JCheckBoxMenuItem();
        cbGuardar = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlCliente.setBackground(new java.awt.Color(247, 255, 247));
        pnlCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 107, 107)), "CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        txtCodigo.setText("11233");
        txtCodigo.setToolTipText("Numérico: Máximo 5 dígitos.");
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        txtNombre.setText("Nombre del cliente");
        txtNombre.setToolTipText("Texto. Máximo 20 caracteres.");
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        jtextfield1.setText("Apellidos del cliente");
        jtextfield1.setToolTipText("Texto. Máximo 30 caracteres.");
        jtextfield1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtextfield1KeyTyped(evt);
            }
        });

        txtDireccion.setText("Dirección del cliente");
        txtDireccion.setToolTipText("Alfanumérico. Máximo 30 caracteres.");

        txtFecha.setText("dd/mm/aaaa");
        txtFecha.setToolTipText("Formato fecha: dd/mm/aaaa");
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaKeyTyped(evt);
            }
        });

        lblTelefono.setText("Teléfono");
        lblTelefono.setToolTipText("Teléfono del cliente");

        lblDireccion.setText("Dirección");
        lblDireccion.setToolTipText("Dirección del cliente");

        lblApellidos.setText("Apellidos");
        lblApellidos.setToolTipText("Apellidos del cliente");

        lblNombre.setText("Nombre ");
        lblNombre.setToolTipText("Nombre del cliente");

        lblCodigo.setText("Código");
        lblCodigo.setToolTipText("Código del cliente");

        jLabel1.setText("Fecha");
        jLabel1.setToolTipText("Fecha del presupuesto");

        txtTelefono1.setText("678112233");
        txtTelefono1.setToolTipText("Numérico. Máximo 9 caracteres.");
        txtTelefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefono1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlClienteLayout = new javax.swing.GroupLayout(pnlCliente);
        pnlCliente.setLayout(pnlClienteLayout);
        pnlClienteLayout.setHorizontalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addComponent(lblTelefono)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefono1))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFecha)
                            .addComponent(txtCodigo))))
                .addGap(83, 83, 83)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlClienteLayout.createSequentialGroup()
                            .addComponent(lblApellidos)
                            .addGap(18, 18, 18)
                            .addComponent(jtextfield1))
                        .addGroup(pnlClienteLayout.createSequentialGroup()
                            .addComponent(lblNombre)
                            .addGap(20, 20, 20)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addComponent(lblDireccion)
                        .addGap(18, 18, 18)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        pnlClienteLayout.setVerticalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidos)
                            .addComponent(jtextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDireccion)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pnlAcciones.setBackground(new java.awt.Color(247, 255, 247));

        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("Guardar presupuesto");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.setToolTipText("Salir del programa");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAccionesLayout = new javax.swing.GroupLayout(pnlAcciones);
        pnlAcciones.setLayout(pnlAccionesLayout);
        pnlAccionesLayout.setHorizontalGroup(
            pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        pnlAccionesLayout.setVerticalGroup(
            pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        pnlServicios.setBackground(new java.awt.Color(247, 255, 247));
        pnlServicios.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 107, 107)), "PRESUPUESTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        lblImagen.setToolTipText("Imagen del trabajo a presupuestar");
        lblImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblImagen.setMaximumSize(new java.awt.Dimension(2, 2));
        lblImagen.setMinimumSize(new java.awt.Dimension(2, 2));
        lblImagen.setName(""); // NOI18N

        cbTrabajo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Instalación de Plato de ducha ", "Aplicar masilla y pintura", "División de tabiques", "Retirada de Escombros " }));
        cbTrabajo.setToolTipText("Tipo de trabajo a presupuestar");
        cbTrabajo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTrabajoItemStateChanged(evt);
            }
        });

        spnCantidad.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        spnCantidad.setToolTipText("Cantidad de trabajos");

        btnAgregar.setBackground(new java.awt.Color(204, 255, 255));
        btnAgregar.setText("Añadir");
        btnAgregar.setToolTipText("Añade trabajo al presupuesto");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jtPresupuesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trabajo", "Cantidad", "Precio"
            }
        ));
        jtPresupuesto.setToolTipText("Listado de trabajos a presupuestar");
        spPresupuesto.setViewportView(jtPresupuesto);

        javax.swing.GroupLayout pnlServiciosLayout = new javax.swing.GroupLayout(pnlServicios);
        pnlServicios.setLayout(pnlServiciosLayout);
        pnlServiciosLayout.setHorizontalGroup(
            pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlServiciosLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServiciosLayout.createSequentialGroup()
                        .addComponent(cbTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar))
                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(spPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        pnlServiciosLayout.setVerticalGroup(
            pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlServiciosLayout.createSequentialGroup()
                        .addGroup(pnlServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        Guardar.setText("Acciones");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        cbMostrarImagenesMenu.setSelected(true);
        cbMostrarImagenesMenu.setText("Mostrar imágenes");
        cbMostrarImagenesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMostrarImagenesMenuActionPerformed(evt);
            }
        });
        Guardar.add(cbMostrarImagenesMenu);

        cbGuardar.setText("Guardar");
        cbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGuardarActionPerformed(evt);
            }
        });
        Guardar.add(cbGuardar);

        Menu.add(Guardar);

        Salir.setText("Salir");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        Menu.add(Salir);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAcciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTrabajoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTrabajoItemStateChanged
        // TODO add your handling code here:
        ImageIcon imagen=new ImageIcon();
        switch(cbTrabajo.getSelectedIndex()){
            case 0:
                imagen=new ImageIcon("recursos/EJ01_02.jpg");
                break;
            case 1:
                imagen=new ImageIcon("recursos/EJ01_03.jpg");
                break;
            case 2:
                imagen=new ImageIcon("recursos/EJ01_04.jpg");
                break;
            case 3:
                imagen=new ImageIcon("recursos/EJ01_05.jpg");
                break;
        }
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
        lblImagen.setIcon(icono);
        this.repaint();     
    }//GEN-LAST:event_cbTrabajoItemStateChanged

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        ImageIcon imagen=new ImageIcon();
        Icon icono;
        
        if (!this.cbMostrarImagenesMenu.getState()){
            imagen=new ImageIcon("img/EJ01_01.jpg");
            icono=new ImageIcon(imagen.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
            lblImagen.setIcon(icono);
            this.repaint();      
        }
        else{ 
            switch(cbTrabajo.getSelectedIndex()){
                case 0:
                    imagen=new ImageIcon("img/EJ01_02.jpg");
                    break;
                case 1:
                    imagen=new ImageIcon("img/EJ01_03.jpg");
                    break;
                case 2:
                    imagen=new ImageIcon("img/EJ01_04.jpg");
                    break;
                case 3:
                    imagen=new ImageIcon("img/EJ01_05.jpg");
                    break;
            }
            icono=new ImageIcon(imagen.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
            lblImagen.setIcon(icono);
            this.repaint();
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm=(DefaultTableModel) jtPresupuesto.getModel();
        switch(cbTrabajo.getSelectedIndex()){
            case 0:
                dtm.addRow(new Object[]{"Instalación plato de ducha", spnCantidad.getValue(), "19.5"});
                break;
            case 1:
                dtm.addRow(new Object[]{"Aplicar masilla y pintura", spnCantidad.getValue(), "12.10"});
                break;
            case 2:
                dtm.addRow(new Object[]{"División de tabiques", spnCantidad.getValue(), "15.99"});
                break;
            case 3:
                dtm.addRow(new Object[]{"Retirada de Escombros", spnCantidad.getValue(), "10.99"});
                break;
        }
        JOptionPane.showMessageDialog(null,"Artículo agregado.");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String errores="";
        String codigo=txtCodigo.getText().toUpperCase();
        String nombre=txtNombre.getText().toUpperCase();
        String apellidos=jtextfield1.getText().toUpperCase();
        String direccion=txtDireccion.getText().toUpperCase();
        String telefono=txtFecha.getText();
       
        
        
        if (!codigo.matches("\\d*") || codigo.isEmpty()) errores+="\n-Error en DNI";
        if (!nombre.matches("[A-Z]*[\\s[A-Z]*]*") || nombre.isEmpty()) errores+="\n-Error en Nombre";
        if (!apellidos.matches("[A-Z]*[\\s[A-Z]*]*") || apellidos.isEmpty()) errores+="\n-Error en Apellidos";
        if (!direccion.matches("[A-Z]*[\\s[A-Z]*]*[0-9]*") || direccion.isEmpty()) errores+="\n-Error en Dirección";
        if (!telefono.matches("[0-9]*") || telefono.isEmpty()) errores+="\n-Error en Teléfono";
        
       
        
        if(errores.isEmpty()){
            System.out.println("Registro Guardado");
            JOptionPane.showMessageDialog(null,"Registro guardado.");
            limpiarFormulario();
            System.exit(0);
        }
        else{
            System.out.println("Errores: " + errores);
            JOptionPane.showMessageDialog(null,errores);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char TestChar=evt.getKeyChar();
        if(!(Character.isLetter(TestChar)) && TestChar!=KeyEvent.VK_SPACE ||  txtNombre.getText().length() >= 20)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
        char TestChar=evt.getKeyChar();
        if(!(Character.isDigit(TestChar))||txtCodigo.getText().length() >= 5)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void jtextfield1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtextfield1KeyTyped
        // TODO add your handling code here:
        char TestChar=evt.getKeyChar();
        if(!(Character.isLetter(TestChar)) && TestChar!=KeyEvent.VK_SPACE ||  jtextfield1.getText().length() >= 30)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jtextfield1KeyTyped

    private void txtFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyTyped
        // TODO add your handling code here:
         char TestChar=evt.getKeyChar();
        if(!(Character.isDigit(TestChar))||txtFecha.getText().length() >= 9)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtFechaKeyTyped

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        if(txtCodigo.getText().length()!=0 || txtNombre.getText().length()!=0 || jtextfield1.getText().length()!=0 || txtDireccion.getText().length()!=0 || txtFecha.getText().length()!=0 || txtFecha.getText().isEmpty()){
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Quiere salir sin guardar los cambios?", "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (respuesta == JOptionPane.YES_OPTION) {
                limpiarFormulario();
                dispose();
            }
        }
        else{
           
            dispose();  //sale porque no se han introducido datos
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cbMostrarImagenesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMostrarImagenesMenuActionPerformed
        // TODO add your handling code here:
        ImageIcon imagen=new ImageIcon();
        Icon icono;
        
        if (!this.cbMostrarImagenesMenu.getState()){
            imagen=new ImageIcon("recursos/EJ01_01.jpg");
            icono=new ImageIcon(imagen.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
            lblImagen.setIcon(icono);
            this.repaint();      
        }
        else{ 
            switch(cbTrabajo.getSelectedIndex()){
                case 0:
                    imagen=new ImageIcon("recursos/EJ01_02.jpg");
                    break;
                case 1:
                    imagen=new ImageIcon("recursos/EJ01_03.jpg");
                    break;
                case 2:
                    imagen=new ImageIcon("recursos/EJ01_04.jpg");
                    break;
                case 3:
                    imagen=new ImageIcon("recursos/EJ01_05.jpg");
                    break;
            }
            icono=new ImageIcon(imagen.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
            lblImagen.setIcon(icono);
            this.repaint();
        }
    }//GEN-LAST:event_cbMostrarImagenesMenuActionPerformed

    private void cbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGuardarActionPerformed

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "¡Adiós!");
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void txtTelefono1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefono1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefono1KeyTyped
    void limpiarFormulario(){
        Component[] componentesClientes = pnlCliente.getComponents();
        for (int i = 0; i < componentesClientes.length; i++) {
            if(componentesClientes[i] instanceof JTextField){
                ((JTextField) componentesClientes[i]).setText("");
            }
            else if(componentesClientes[i] instanceof JFormattedTextField){
                ((JFormattedTextField) componentesClientes[i]).setText("");
            }
        }
     
        DefaultTableModel model = (DefaultTableModel) this.jtPresupuesto.getModel();
       // int[] rows = jtProductos.getSelectedRows();
       
        int rowslong = model.getRowCount();
        // i=1, 0  i=2 , 1 i=3 2 i=4 3
        for (int i = rowslong; i > 0; i--) {
            model.removeRow(i-1);
           
        }
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroducirReforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroducirReforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroducirReforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroducirReforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IntroducirReforma dialog = new IntroducirReforma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Guardar;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu Salir;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuItem cbGuardar;
    private javax.swing.JCheckBoxMenuItem cbMostrarImagenesMenu;
    private javax.swing.JComboBox cbTrabajo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jtPresupuesto;
    private javax.swing.JTextField jtextfield1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JPanel pnlAcciones;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JPanel pnlServicios;
    private javax.swing.JScrollPane spPresupuesto;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono1;
    // End of variables declaration//GEN-END:variables
}
